#!/opt/homebrew/bin/bash

# adding this directly because for some reason tmux and fzf pop-up doesn't read from .zshrc
FZF_DEFAULT_OPTS="--reverse --margin 0% --padding 0%"

tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    sed '/^$/d' |\
    fzf $FZF_DEFAULT_OPTS --header 'Jump to session' --preview 'tmux capture-pane -pt {}'  |\
    xargs tmux switch-client -t


