#!/opt/homebrew/bin/bash
#
# Lists workspaces and changes the session or creates a new one if it doesn't exist
#
# - The root dir for the session is the project directory

# adding this directly because when calling from tmux via the display pop-up the defaults don't load from .zshrc
FZF_DEFAULT_OPTS="--reverse --margin 0% --padding 0%"

declare -A hashmap

fd_output=$(fd . ~/Projects/ -d 1 --type d)

while read -r workspace_path; do
    workspace_name=$(basename "$workspace_path")
    hashmap["$workspace_name"]="$workspace_path"
done <<< "$fd_output"

echo "${!hashmap[@]}" | \
tr ' ' '\n' | \
fzf $FZF_DEFAULT_OPTS \
    --header "session: enter  |  window: ctrl-w |  below: ctrl-w  |  above: ctrl-k  |  left: ctrl-h  |  right: ctrl-l" \
    --bind='enter:become(~/bin/shellscripts/list-workspaces-subscripts/open_workspace_in_session {})' \
    --bind='ctrl-w:become(~/bin/shellscripts/list-workspaces-subscripts/open_workspace_in_window {})' \
    --bind='ctrl-l:become(~/bin/shellscripts/list-workspaces-subscripts/open_workspace_in_h_pane {})' \
    --bind='ctrl-h:become(~/bin/shellscripts/list-workspaces-subscripts/open_workspace_in_h_pane {} -b)' \
    --bind='ctrl-j:become(~/bin/shellscripts/list-workspaces-subscripts/open_workspace_in_v_pane {})' \
    --bind='ctrl-k:become(~/bin/shellscripts/list-workspaces-subscripts/open_workspace_in_v_pane {} -b)'

